### PR TITLE
fix: color of objects and constructors

### PR DESCRIPTION
**Pull request by tunnckoCore**
color of object and object property; color of constructor calling with new - in cases like new TypeError(message)

**before**
2017-01-18-17 52 26_1280x1024_scrot

**after** (notice L63, L83 and L94-95)
2017-01-18-17 51 32_1280x1024_scrot

**sublime**
2017-01-18-17 52 50_1280x1024_scrot

### CODE REVIEW

**Comment by silvestreh** [comment]
Looks good! Merging… (and thanks!)

**Comment by tunnckoCore** [comment]
Great! :taco:

**Comment by tunnckoCore** [comment]
Hm. Maybe I introduced a bug ;d Notice the `const resolvePluginsSync` on line 60 it is white as all const should be, but it is function assignment so it should be blue too.

**Comment by silvestreh** [comment]
Looks like a bug with the highlight "engine"… it's doesn't consider it a function if the `const` keyword precedes it.

**Comment by tunnckoCore** [comment]
Yea, it works when you use `let` and `var`. Where should report it? Or can you report it because Im not so atom user, i'm new.

**Pull request merged**
